### ISSUE TITLE
docker build fails

### ISSUE THREAD

**Issue by ARekesh** [NVIDIA/cheminformatics#79]
The FROM statement points to an image that appears to be private. Please advise on the location of a public alternative

https://github.com/NVIDIA/cheminformatics/blob/a86ed80cf47d5f8ea7a0e4af3478c649da4b412b/Dockerfile.megamolbart#L2

**Comment by rilango** [comment]
Hi ARekesh,

Sorry for the late reply. This issue is mainly due to dependency on between training and inference component. We are working towards publishing training artifacts. In the mean while please use the pre-build containers from NGC. https://ngc.nvidia.com/catalog/resources/nvidia:clara:cheminformatics

**Comment by rilango** [comment]
Fixed  3524a4bbf3e15f8586bcb0190ffa66fc9398db78
